kakao-tech-campus-2nd-step3/Team2_BE

Dockerfile, compose.yml
이미지를 생성하는 DockerFile과 이미지와 db를 함께 실행하는 compose.yml을 작성하였습니다
compose.yml은 임시로 경로를 달아 놓았으니 후에 수정할 예정입니다.
=> feat: DockerFile로 이미지 생성 

src/main/java/jeje/work/aeatbe/dto/AllergyCategoryDTO.java, src/main/java/jeje/work/aeatbe/dto/ArticleDTO.java, src/main/java/jeje/work/aeatbe/dto/ProductDTO.java, src/main/java/jeje/work/aeatbe/dto/UserDTO.java, src/main/java/jeje/work/aeatbe/dto/WishlistDTO.java, src/main/java/jeje/work/aeatbe/entity/AllergyCategory.java, src/main/java/jeje/work/aeatbe/entity/Article.java, src/main/java/jeje/work/aeatbe/entity/Product.java, src/main/java/jeje/work/aeatbe/entity/User.java, src/main/java/jeje/work/aeatbe/entity/Wishlist.java
lombok을 사용한 entity, dto 구현 개선 완료.
실수로 새 브랜치를 파서 push해버렸는데, 수정된 부분은 여기 있으니 이 코드 보시고 둘 다 merge 판단하시면 될 것 같습니다.
=> refactor: lombok으로 재구현

src/main/java/jeje/work/aeatbe/dto/FreeFromCategoryDTO.java, src/main/java/jeje/work/aeatbe/dto/ProductAllergyDTO.java, src/main/java/jeje/work/aeatbe/dto/ProductFreeFromDTO.java, src/main/java/jeje/work/aeatbe/dto/UserAllergyDTO.java, src/main/java/jeje/work/aeatbe/dto/UserFreeFromDTO.java, src/main/java/jeje/work/aeatbe/entity/FreeFromCategory.java, src/main/java/jeje/work/aeatbe/entity/ProductAllergy.java, src/main/java/jeje/work/aeatbe/entity/ProductFreeFrom.java, src/main/java/jeje/work/aeatbe/entity/UserAllergy.java, src/main/java/jeje/work/aeatbe/entity/UserFreeFrom.java
- free_from_categories,
- users_allergies,
- users_free_from,
- products_allergies,
- products_freefrom의 Entity와 DTO를 구성하였습니다
=> feat : Entity, DTO 구현

src/main/java/jeje/work/aeatbe/AeatbeApplication.java, src/main/java/jeje/work/aeatbe/dto/AllergyCategoryDTO.java, src/main/java/jeje/work/aeatbe/dto/ArticleDTO.java, src/main/java/jeje/work/aeatbe/dto/FreeFromCategoryDTO.java, src/main/java/jeje/work/aeatbe/dto/ProductDTO.java, src/main/java/jeje/work/aeatbe/dto/UserDTO.java, src/main/java/jeje/work/aeatbe/dto/WishlistDTO.java, src/main/java/jeje/work/aeatbe/entity/AllergyCategory.java, src/main/java/jeje/work/aeatbe/entity/Article.java, src/main/java/jeje/work/aeatbe/entity/BaseEntity.java, src/main/java/jeje/work/aeatbe/entity/FreeFromCategory.java, src/main/java/jeje/work/aeatbe/entity/Product.java, src/main/java/jeje/work/aeatbe/entity/ProductAllergy.java, src/main/java/jeje/work/aeatbe/entity/ProductFreeFrom.java, src/main/java/jeje/work/aeatbe/entity/User.java, src/main/java/jeje/work/aeatbe/entity/UserAllergy.java, src/main/java/jeje/work/aeatbe/entity/UserFreeFrom.java, src/main/java/jeje/work/aeatbe/entity/Wishlist.java
필요없는 어노테이션 삭제, TimeStamp사용을 위한 Entity들 BaseEntity상속으로 변경
=> refactor: BaseEntity상속으로 수정

src/main/java/jeje/work/aeatbe/dto/AllergyCategoryDTO.java, src/main/java/jeje/work/aeatbe/dto/ArticleDTO.java, src/main/java/jeje/work/aeatbe/dto/FreeFromCategoryDTO.java, src/main/java/jeje/work/aeatbe/dto/ProductAllergyDTO.java, src/main/java/jeje/work/aeatbe/dto/ProductDTO.java, src/main/java/jeje/work/aeatbe/dto/ProductFreeFromDTO.java, src/main/java/jeje/work/aeatbe/dto/UserAllergyDTO.java, src/main/java/jeje/work/aeatbe/dto/UserDTO.java, src/main/java/jeje/work/aeatbe/dto/UserFreeFromDTO.java, src/main/java/jeje/work/aeatbe/dto/WishlistDTO.java, src/main/java/jeje/work/aeatbe/entity/AllergyCategory.java, src/main/java/jeje/work/aeatbe/entity/Article.java, src/main/java/jeje/work/aeatbe/entity/FreeFromCategory.java, src/main/java/jeje/work/aeatbe/entity/Product.java, src/main/java/jeje/work/aeatbe/entity/ProductAllergy.java, src/main/java/jeje/work/aeatbe/entity/ProductFreeFrom.java, src/main/java/jeje/work/aeatbe/entity/User.java, src/main/java/jeje/work/aeatbe/entity/UserAllergy.java, src/main/java/jeje/work/aeatbe/entity/UserFreeFrom.java, src/main/java/jeje/work/aeatbe/entity/Wishlist.java, src/test/java/jeje/work/aeatbe/entity/FreeFromCategoryTest.java, src/test/java/jeje/work/aeatbe/entity/ProductAllergyTest.java, src/test/java/jeje/work/aeatbe/entity/ProductFreeFromTest.java, src/test/java/jeje/work/aeatbe/entity/UserAllergyTest.java, src/test/java/jeje/work/aeatbe/entity/UserFreeFromTest.java
- 무분별한 객체 생성 방지를 위해 모든 Entity 클래스 내에 기본 생성자의 접근 제한자를 public -> protected로 변경하였습니다.
- null 사용을 위해 각 Entity 내의 PK의 자료형을 Long type으로 수정하였습니다.
=> fix(entity, dto) :  기본 생성자의 접근 제한자 변경 및 PK 자료형 수정

src/main/java/jeje/work/aeatbe/repository/AllergyCategoryRepository.java, src/main/java/jeje/work/aeatbe/repository/ArticleRepository.java, src/main/java/jeje/work/aeatbe/repository/FreeFromCategoryRepository.java, src/main/java/jeje/work/aeatbe/repository/ProductAllergyRepository.java, src/main/java/jeje/work/aeatbe/repository/ProductFreeFromRepository.java, src/main/java/jeje/work/aeatbe/repository/ProductRepository.java, src/main/java/jeje/work/aeatbe/repository/UserAllergyRepository.java, src/main/java/jeje/work/aeatbe/repository/UserFreeFromRepository.java, src/main/java/jeje/work/aeatbe/repository/UserRepository.java, src/main/java/jeje/work/aeatbe/repository/WishlistRepository.java
- repository 클래스들 내에 @Repository 어노테이션이 빠진 것 같아 적용하였습니다
=> fix(repository) : @Repository 어노테이션 적용

src/main/java/jeje/work/aeatbe/controller/ArticleLikeController.java, src/main/java/jeje/work/aeatbe/dto/ArticleLikeRequestDTO.java, src/main/java/jeje/work/aeatbe/dto/ArticleLikeResponseDTO.java, src/main/java/jeje/work/aeatbe/entity/Article.java, src/main/java/jeje/work/aeatbe/entity/ArticleLike.java, src/main/java/jeje/work/aeatbe/entity/User.java, src/main/java/jeje/work/aeatbe/exception/GlobalExceptionHandler.java, src/main/java/jeje/work/aeatbe/exception/NotFoundColumnException.java, src/main/java/jeje/work/aeatbe/exception/NotFoundUserException.java, src/main/java/jeje/work/aeatbe/repository/AllergyCategoryRepository.java, src/main/java/jeje/work/aeatbe/repository/ArticleLikeRepository.java, src/main/java/jeje/work/aeatbe/repository/ArticleRepository.java, src/main/java/jeje/work/aeatbe/repository/FreeFromCategoryRepository.java, src/main/java/jeje/work/aeatbe/repository/ProductAllergyRepository.java, src/main/java/jeje/work/aeatbe/repository/ProductFreeFromRepository.java, src/main/java/jeje/work/aeatbe/repository/ProductRepository.java, src/main/java/jeje/work/aeatbe/repository/UserAllergyRepository.java, src/main/java/jeje/work/aeatbe/repository/UserFreeFromRepository.java, src/main/java/jeje/work/aeatbe/repository/UserRepository.java, src/main/java/jeje/work/aeatbe/repository/WishlistRepository.java, src/main/java/jeje/work/aeatbe/service/ArticleLikeService.java, src/test/java/jeje/work/aeatbe/EntityRepositoryTests.java
칼럼 좋아요 api를 구현했습니다. 현재 로그인 로직이 구현되어있지 않은관계로 임의로 쿼리파라미터로 유저 ID를 입력받게했습니다. 로그인 로직이 구현한후 다시 이에맞춰 코드를 수정할 필요가 있을것같습니다.
=> feat:칼럼좋아요 api구현

src/main/java/jeje/work/aeatbe/controller/WishListController.java, src/main/java/jeje/work/aeatbe/dto/ProductDTO.java, src/main/java/jeje/work/aeatbe/dto/article/ArticleDTO.java, src/main/java/jeje/work/aeatbe/dto/article/ArticleListResponseDTO.java, src/main/java/jeje/work/aeatbe/dto/article/ArticleResponseDTO.java, src/main/java/jeje/work/aeatbe/dto/article/ContentDTO.java, src/main/java/jeje/work/aeatbe/dto/article/PageInfoDTO.java, src/main/java/jeje/work/aeatbe/dto/wishlist/WishDTO.java, src/main/java/jeje/work/aeatbe/dto/wishlist/WishProductDTO.java, src/main/java/jeje/work/aeatbe/entity/Article.java, src/main/java/jeje/work/aeatbe/entity/Product.java, src/main/java/jeje/work/aeatbe/exception/GlobalExceptionHandler.java, src/main/java/jeje/work/aeatbe/exception/WishlistNotFoundException.java, src/main/java/jeje/work/aeatbe/repository/ArticleRepository.java, src/main/java/jeje/work/aeatbe/repository/WishlistRepository.java, src/main/java/jeje/work/aeatbe/service/ArticleService.java, src/main/java/jeje/work/aeatbe/service/WishListService.java, src/test/java/jeje/work/aeatbe/ArticleServiceTest.java, src/test/java/jeje/work/aeatbe/EntityRepositoryTests.java, src/test/java/jeje/work/aeatbe/WishListServiceTest.java
wishlist 구현과 더불여 여러 이슈들을 해결했습니다. 
builder 적용
required-false인 파라미터들 미입력 시 칼럼리스트 전체 반환 추가
=> feat: wishlist구현

src/main/java/jeje/work/aeatbe/controller/WishListController.java, src/main/java/jeje/work/aeatbe/service/WishListService.java, src/test/java/jeje/work/aeatbe/WishListServiceTest.java
wishlist crud 구현할때 리뷰로 요청받았던 부분 수정
인증토큰 방식을 LoginUserId 사용으로 변경하였습니다.
=> fix: 인증 토큰 방식을 userId로 변경

src/main/java/jeje/work/aeatbe/config/WebConfig.java, src/main/java/jeje/work/aeatbe/controller/ArticleLikeController.java, src/main/java/jeje/work/aeatbe/controller/KakaoAuthController.java, src/main/java/jeje/work/aeatbe/controller/ReviewController.java, src/main/java/jeje/work/aeatbe/controller/WishListController.java, src/main/java/jeje/work/aeatbe/entity/User.java, src/main/java/jeje/work/aeatbe/repository/ArticleLikeRepository.java, src/main/java/jeje/work/aeatbe/repository/UserRepository.java, src/main/java/jeje/work/aeatbe/resolver/LoginUserArgumentResolver.java, src/main/java/jeje/work/aeatbe/service/ArticleLikeService.java, src/main/java/jeje/work/aeatbe/service/KakaoService.java, src/main/java/jeje/work/aeatbe/service/ReviewService.java, src/main/java/jeje/work/aeatbe/service/UserService.java, src/main/java/jeje/work/aeatbe/service/WishListService.java, src/main/java/jeje/work/aeatbe/utility/JwtUtil.java, src/test/java/jeje/work/aeatbe/WishListServiceTest.java
제 파트 7/8주차 리뷰를 반영하고
지난주 의견을 받들어 @LoginUser를 기존 kakaoId에서 user의 Id(PK)를 주입하는 로직으로 변경했습니다
또한 userId가 헷갈리는거같아 kakaoId로 변경하였습니다
#63 
오늘부터 시험이끝나 개발에 들어가는 분들이 많아서  이번에 공통적으로 활용될 사항들이 담겨있어 작은단위로 pr보냅니다
=> Refactor: 7/8주차 리뷰 반영 및 UserId활용으로 변경

src/main/java/jeje/work/aeatbe/controller/ProductController.java, src/main/java/jeje/work/aeatbe/controller/ReviewController.java, src/main/java/jeje/work/aeatbe/dto/product/ProductResponseDTO.java, src/main/java/jeje/work/aeatbe/entity/ProductAllergy.java, src/main/java/jeje/work/aeatbe/entity/ProductFreeFrom.java, src/main/java/jeje/work/aeatbe/entity/UserAllergy.java, src/main/java/jeje/work/aeatbe/entity/UserFreeFrom.java, src/main/java/jeje/work/aeatbe/repository/ProductRepository.java, src/main/java/jeje/work/aeatbe/service/ProductService.java, src/main/java/jeje/work/aeatbe/service/ReviewService.java, src/test/java/jeje/work/aeatbe/service/ProductServiceTest.java
- 상품 컨트롤러를 구성하였습니다.
- 컨트롤러를 위해 서비스 로직에 getAllProducts 메서드를 추가하였습니다.
- 다른 서비스 로직들에 변경이 필요한 주석들을 수정하였습니다.
- 테스트를 할때마다 경고가 떠서 @EqualsAndHashCode(callSuper = false)로 설정해뒀습니다
+ 상품 테스트 코드는 계속 문제가 생겨서 천천히 다시 짜본 후 pr 넣도록 하겠습니다
=> feat : 상품 컨트롤러

src/main/java/jeje/work/aeatbe/dto/article/PageInfoDTO.java, src/main/java/jeje/work/aeatbe/service/ArticleService.java, src/test/java/jeje/work/aeatbe/ArticleServiceTest.java, src/test/java/jeje/work/aeatbe/WishListServiceTest.java, src/test/java/jeje/work/aeatbe/entity/AllergyCategoryTest.java, src/test/java/jeje/work/aeatbe/entity/ArticleLikeTest.java, src/test/java/jeje/work/aeatbe/entity/ArticleTest.java, src/test/java/jeje/work/aeatbe/entity/ProductTest.java, src/test/java/jeje/work/aeatbe/entity/ReviewTest.java, src/test/java/jeje/work/aeatbe/entity/UserTest.java, src/test/java/jeje/work/aeatbe/entity/WishlistTest.java
기존의 엔티티 테스트를 참고해서 나머지 엔티티 테스트를 구현했습니다.
하는 김에 wishlist service도 다른 테스트 참고해서 좀 개선해봤는데 이것도 너무 별로같으면 삭제하도록 하겠습니다. 
페이지네이션 토큰 문제 및 api명세에 맞게 멤버 이름 변경도 해결했습니다.
=> test: entity

.github/workflows/spring_test.yml
Reverts kakao-tech-campus-2nd-step3/Team2_BE#72
=> Revert "Update spring_test.yml"

src/main/java/jeje/work/aeatbe/dto/product/ProductResponseDTO.java
- productResponseDTO 내 사용하지 않는 필드를 삭제하였습니다
=> chore :  불필요한 필드 삭제

src/main/java/jeje/work/aeatbe/dto/review/ReviewDTO.java
- reviewDTO내 productImgUrl을 String type으로 수정 후 @Nullable을 적용하였습니다
=> refactor : reviewDTO 내 productImgUrl 필드 타입 변경

src/main/java/jeje/work/aeatbe/dto/review/ReviewDTO.java, src/main/java/jeje/work/aeatbe/service/ReviewService.java
- productImgUrl의 필드 타입을 Optional<String>에서 String으로 변경하였습니다.
=> refactor : productImgUrl 필드 타입 변경

src/main/java/jeje/work/aeatbe/controller/ArticleLikeController.java, src/main/java/jeje/work/aeatbe/controller/TokenController.java
articleLike delete 로직이 잘못된걸 수정했습니다
=> fix: articleLike delete 수정

src/main/java/jeje/work/aeatbe/dto/review/ReviewDTO.java, src/main/java/jeje/work/aeatbe/dto/review/ReviewResponseDTO.java, src/main/java/jeje/work/aeatbe/mapper/Review/ReviewMapper.java, src/main/java/jeje/work/aeatbe/mapper/Review/ReviewResponseMapper.java, src/main/java/jeje/work/aeatbe/service/ReviewService.java
myReview에서 상품명과 수정날짜를 받게 수정하였습니다.
=> refactor: myReview에서 상품명, 수정날짜 받게 설정

src/main/java/jeje/work/aeatbe/config/WebConfig.java, src/main/java/jeje/work/aeatbe/controller/ArticleLikeController.java, src/main/java/jeje/work/aeatbe/dto/articleLike/ArticleLikeCountResponseDTO.java, src/main/java/jeje/work/aeatbe/dto/articleLike/IsLikedResponseDTO.java, src/main/java/jeje/work/aeatbe/interceptor/JwtInterceptor.java, src/main/java/jeje/work/aeatbe/resolver/LoginUserArgumentResolver.java
ArticleLike에 관해 바뀐 명세에 대해 분리를 진행하였습니다
=> feat: 바뀐 명세에 따른 메서드 분리

src/main/java/jeje/work/aeatbe/dto/product/ProductResponseDTO.java, src/main/java/jeje/work/aeatbe/mapper/product/ProductResponseMapper.java
- 상품 용량, 제조사, 태그, 영양성분, 원재료 필드 추가
=> feat : ProductResponseDTO 필드 추가
